Tranpose operation seems to be working nicely.
Concerns for later:
+ Optional arugment for dims, transpose, and mean. What to output if
there's no argument?
+ Make it possible to read data in from stdin instead of file, so the
pipeline works.

diff --git a/projects/1/matrix b/projects/1/matrix
--- a/projects/1/matrix
+++ b/projects/1/matrix
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/bin/bash -x
 
 #######################################################
 # TITLE: matrix                                       #
@@ -42,14 +42,26 @@ _usage() {
   echo -e "  multiply \tMultiply an (m x n) and a (n x p) matrix" 1>&2
   echo -e "  test \t\tPrints 'Hello, world!'" 1>&2
   echo -e "  help \t\tPrints this message" 1>&2
-  echo
+  echo 1>&2
   exit 1
+}
+
+_usage_dims() {
+  echo -e "Usage: $0 $1 [\033[4mMATRIX\033[0m]" 1>&2
+  echo 1>&2
+  exit 1
+}
+
+_usage_transpose() {
+  # Same as _usage_dims
+  _usage_dims $1
 }
 
 # Check if file exists, print an error if it doesn't
 _fileExists() {
   if [ ! -f $1 ]; then
     echo "$1: No such file" 1>&2
+    echo 1>&2
     exit 1
   fi
 }
@@ -58,6 +70,7 @@ _fileExists() {
 _fileIsReadable() {
   if [ ! -r $1 ]; then
     echo "$1: File is unreadable" 1>&2
+    echo 1>&2
     exit 1
   fi
 }
@@ -93,6 +106,10 @@ _countCols() {
 
 # Find dimensions of a matrix in file $1
 dims() {
+  if [ $# -eq 0 ]; then
+    _usage_dims dims
+  fi
+
   _fileExists $1
   _fileIsReadable $1
 
@@ -104,6 +121,50 @@ dims() {
 
   exit 0
 }
+
+# Transpose a matrix from file and print it to stdout
+transpose() {
+  if [ $# -eq 0 ]; then
+    _usage_transpose transpose
+  fi
+  
+  _fileExists $1
+  _fileIsReadable $1
+
+  tempCol=".col-$$"
+  temp=".tmp-$$"
+
+  clean="cleaning up and exiting"
+  trap "echo -e '\nSIGINT: $clean' 1>&2; rm -f $temp $tempCol; exit 1" INT
+  trap "echo -e '\nSIGHUP: $clean' 1>&2; rm -f $temp $tempCol; exit 1" HUP
+  trap "echo -e '\nSIGTERM: $clean' 1>&2; rm -f $temp $tempCol; exit 1" TERM
+
+  # Get matrix dimensions
+  inDims=`matrix dims $1`
+  inRows=`echo $inDims | cut -s -d " " -f 1`
+  inCols=`echo $inDims | cut -s -d " " -f 2`
+
+  for c in `seq 1 $inCols`; do
+    # Cut the column and save it to temp file
+    cut -s -f $c $1 > $tempCol
+
+    # Write each element in column to a tab-delim row in temp file
+    while read el; do
+      printf "$el\t" >> $temp
+    done < $tempCol
+
+    # Newline at end of each row
+    printf "\n" >> $temp
+  done
+
+  # echo new matrix
+  cat $temp
+
+  # Clean up
+  rm -f $temp $tempCol
+  exit 0
+}
+
 
 ################
 # MAIN ROUTINE #
